/* soapSectionnerService.h
   Generated by gSOAP 2.8.55 for E:\Projects\WebService\GeneratedCode\Sectionner\source\WebService\source.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapSectionnerService_H
#define soapSectionnerService_H
#include "soapH.h"

    class SOAP_CMAC SectionnerService {
      public:
        /// Context to manage service IO and data
        struct soap *soap;
        bool soap_own;  ///< flag indicating that this context is owned by this service when context is shared
        /// Variables globally declared in E:\Projects\WebService\GeneratedCode\Sectionner\source\WebService\source.h, if any
        /// Construct a service with new managing context
        SectionnerService();
        /// Copy constructor
        SectionnerService(const SectionnerService&);
        /// Construct service given a shared managing context
        SectionnerService(struct soap*);
        /// Constructor taking input+output mode flags for the new managing context
        SectionnerService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        SectionnerService(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~SectionnerService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void SectionnerService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual SectionnerService *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        SectionnerService& operator=(const SectionnerService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve this request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a request (returns SOAP_OK or error code)
        virtual int dispatch();
        virtual int dispatch(struct soap *soap);
        ///
        /// Service operations are listed below (you should define these)
        /// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
        ///
        /// Web service operation 'GetDeviceStatus' (returns SOAP_OK or error code)
        virtual int GetDeviceStatus(const ns__User& requestUser, const ns__Device& requestDevice, ns__Device &responseDevice) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetDeviceStatusSMS' (returns SOAP_OK or error code)
        virtual int GetDeviceStatusSMS(const ns__User& requestUser, const ns__Device& requestDevice, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetAllDeviceStatus' (returns SOAP_OK or error code)
        virtual int GetAllDeviceStatus(const ns__User& requestUser, ns__UserDevice &responseUserDevices) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetDevicePicture' (returns SOAP_OK or error code)
        virtual int GetDevicePicture(const ns__User& requestUser, const ns__Device& requestDevice, ns__Device &responseDevice) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetDevicePicturePart' (returns SOAP_OK or error code)
        virtual int GetDevicePicturePart(const ns__User& requestUser, const ns__Device& requestDevice, ns__Device &responseDevice) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetDeviceSetting' (returns SOAP_OK or error code)
        virtual int SetDeviceSetting(const ns__User& requestUser, const ns__Device& requestDevice, std::vector<ns__ErrorCode> &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetDeviceSettingSMS' (returns SOAP_OK or error code)
        virtual int SetDeviceSettingSMS(const ns__User& requestUser, const ns__Device& requestDevice, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetAllDeviceSetting' (returns SOAP_OK or error code)
        virtual int SetAllDeviceSetting(const ns__User& requestUser, std::vector<ns__Device> requestDevice, std::vector<ns__ErrorCode> &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteDevices' (returns SOAP_OK or error code)
        virtual int DeleteDevices(const ns__User& requestUser, std::vector<ns__Device> requestDeviceList, std::vector<ns__ErrorCode> &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetDeviceCalibration' (returns SOAP_OK or error code)
        virtual int SetDeviceCalibration(const ns__User& requestUser, const ns__Device& requestDevice, const ns__CalibrationList& requestCalibrationList, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetDeviceCalibration' (returns SOAP_OK or error code)
        virtual int GetDeviceCalibration(const ns__User& requestUser, const ns__Device& requestDevice, ns__CalibrationList &responsCalibrationList) SOAP_PURE_VIRTUAL;
        /// Web service operation 'Login' (returns SOAP_OK or error code)
        virtual int Login(const ns__User& requestUser, ns__User &responseUser) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetUserDeviceList' (returns SOAP_OK or error code)
        virtual int GetUserDeviceList(const ns__User& requestUser, ns__UserDevice &responseUserDevices) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetUsersList' (returns SOAP_OK or error code)
        virtual int GetUsersList(const ns__User& requestUser, ns__UsersList &responseUsersList) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AddUser' (returns SOAP_OK or error code)
        virtual int AddUser(const ns__User& requestUser, const ns__User& requestNewUser, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'UpdateUser' (returns SOAP_OK or error code)
        virtual int UpdateUser(const ns__User& requestUser, const ns__User& requestNewUser, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteUser' (returns SOAP_OK or error code)
        virtual int DeleteUser(const ns__User& requestUser, const ns__User& requestDeleteUser, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AssignDeviceToUser' (returns SOAP_OK or error code)
        virtual int AssignDeviceToUser(const ns__User& requestUser, const ns__UserDevice& requestUserDevice, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteDeviceFromUser' (returns SOAP_OK or error code)
        virtual int DeleteDeviceFromUser(const ns__User& requestUser, const ns__UserDevice& requestUserDevice, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetUserDevices' (returns SOAP_OK or error code)
        virtual int GetUserDevices(const ns__User& requestUser, const ns__User& requestSelectedUser, ns__UserDevice &responseUserDevices) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SaveActivityLog' (returns SOAP_OK or error code)
        virtual int SaveActivityLog(const ns__User& requestUser, const ns__ActivityLog& requestActivityLog, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetActivityLog' (returns SOAP_OK or error code)
        virtual int GetActivityLog(const ns__User& requestUser, const ns__ReportRange& requestReport, std::vector<ns__ActivityLog> &responseActivityLog) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SaveUserLog' (returns SOAP_OK or error code)
        virtual int SaveUserLog(const ns__User& requestUser, const ns__UserLog& requestActivityLog, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetUserLog' (returns SOAP_OK or error code)
        virtual int GetUserLog(const ns__User& requestUser, const ns__ReportRange& requestReport, std::vector<ns__UserLog> &responseActivityLog) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SaveDeviceStatusLog' (returns SOAP_OK or error code)
        virtual int SaveDeviceStatusLog(const ns__User& requestUser, const ns__DeviceStatusLog& requestStatusLog, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetDeviceStatusLog' (returns SOAP_OK or error code)
        virtual int GetDeviceStatusLog(const ns__User& requestUser, const ns__DeviceStatus& requestStatusLog, ns__DeviceStatusLogList &responseStatusLogList) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetServerOptions' (returns SOAP_OK or error code)
        virtual int GetServerOptions(const ns__User& requestUser, ns__ServerOptions &serverOptions) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetServerOptions' (returns SOAP_OK or error code)
        virtual int SetServerOptions(const ns__User& requestUser, const ns__ServerOptions& serverOptions, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCityAndLocations' (returns SOAP_OK or error code)
        virtual int GetCityAndLocations(const ns__User& requestUser, ns__AllCityLocatoins &responseCityLocation) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ChangeCityName' (returns SOAP_OK or error code)
        virtual int ChangeCityName(const ns__User& requestUser, const std::string& oldCityName, const std::string& newCityName, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ChangeLocationName' (returns SOAP_OK or error code)
        virtual int ChangeLocationName(const ns__User& requestUser, const std::string& oldCityName, const std::string& newCityName, const std::string& oldLocationName, const std::string& newLocationName, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ChangeDeviceName' (returns SOAP_OK or error code)
        virtual int ChangeDeviceName(const ns__User& requestUser, int deviceSerialNumber, const std::string& newCityName, const std::string& newLocationName, const std::string& newDeviceName, ns__ErrorCode &responseError) SOAP_PURE_VIRTUAL;
    };
#endif
